repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        entry: cargo fmt
        language: system
        args: [--all, --check, --]
        pass_filenames: false

      - id: clippy
        name: clippy
        entry: cargo clippy
        language: system
        args: [--all-targets, --all-features, --, -D, warnings]
        pass_filenames: false