repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs

  - repo: local
    hooks:
      - id: rust-pre-commit
        name: Rust pre-commit checks
        entry: ./scripts/pre-commit-rust.sh
        language: script
        files: '\.(rs|toml)$'
        pass_filenames: false
