DROP TABLE IF EXISTS oauth_accounts;
DROP TYPE IF EXISTS oauth_provider;

ALTER TABLE users
    ADD COLUMN IF NOT EXISTS google_sub VARCHAR(255) UNIQUE,
    ADD COLUMN IF NOT EXISTS google_picture VARCHAR(255),
    ADD COLUMN IF NOT EXISTS email_verified BOOLEAN NOT NULL DEFAULT FALSE;

